### ISSUE TITLE
incorporate reprocess all ontologies workflow from ncbo_migration project to ncbo_cron

### ISSUE THREAD

**Issue by alexskr** [ncbo/ncbo_cron#15]
we use reprocess script from ncbo_migration project to reprocess all ontologies when we load new versions of UMLS.  It makes sense to move it to ncbo_cron project.

https://github.com/ncbo/ncbo_migration/blob/master/workflows/reprocess.rb

**Comment by graybeal** [comment]
Alex to talk to Misha, may just require proper documentation.

**Comment by alexskr** [comment]
documentation is in place
