### ISSUE TITLE
Are mappings generated as part of the cron job?

### ISSUE THREAD

**Issue by turbomam** [ncbo/ncbo_cron#29]
I really like the BioPortal in general and especially the term mapper. I'd like to retrieve a large number of mappings on a frequent basis, so I was thinking of doing that in the AWS appliance.

IS that possible? Would any of the virtual BioPortal appliances generate mappings, either as part of the corn job, or by some other trigger?

**Comment by turbomam** [comment]
Ah, I see that mappings were generated for two ontologies I loaded into an AWS instance some time ago.

If you have any insights to share with me regarding this process, I'd love to hear them.

For example, with local access to the server, can I retrieve the mappings through any method other than the REST API? Like 4store or Redis?

Otherwise, you can close this issue.

**Comment by graybeal** [comment]
Is it OK if we start a response thread on the BioPortal Support list? That will be a better place to present all this information, others may also contribute.

**Comment by turbomam** [comment]
of course. do you mean the email list? do you need me to do anything?

**Comment by graybeal** [comment]
If you want to send your question to that list it would be great (support@bioontology.org<mailto:support@bioontology.org>). Signing up for the list is a minor plus, not required.

john

**Comment by turbomam** [comment]
thanks. sent "term mapping experience in BioPortal appliance"
