### ISSUE TITLE
disable sending email notifications when ontologies are manually processed from command line or UI admin interface

### ISSUE THREAD

**Issue by alexskr** [ncbo/ncbo_cron#77]

**Comment by jvendetti** [comment]
For the sake of completeness, this ticket is about an unintended side-effect of the notifications functionality that was recently revived.

Changes to the code base to support searching by short ID required a reprocessing of all ontologies in BioPortal. When the reprocessing was initiated, the system started broadcasting notifications to all ontology administrators that they're ontologies had been processed.

The desired functionality here is to only send processing notifications when users submit new versions of their ontologies, but not when we're performing system administrative tasks like reprocessing for troubleshooting purposes, ingesting the UMLS releases, etc.
